#!/usr/bin/env bash
# =============================================================================
# setup-design.sh - Prepare design environment for a feature
# =============================================================================
# Usage:
#   ./setup-design.sh [feature-dir]
#   ./setup-design.sh --json [feature-dir]
#
# Outputs:
#   - Text mode: Human-readable summary
#   - JSON mode: Machine-readable output for parsing
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
BRAND_FILE="$REPO_ROOT/.specify/brand/brand.yaml"
TEMPLATE_FILE="$REPO_ROOT/.specify/templates/design-template.md"

# Source common functions
if [[ -f "$SCRIPT_DIR/common.sh" ]]; then
    source "$SCRIPT_DIR/common.sh"
fi

# =============================================================================
# Get feature directory
# =============================================================================
get_feature_dir() {
    # Priority 1: SPECIFY_FEATURE environment variable
    if [[ -n "${SPECIFY_FEATURE:-}" ]]; then
        echo "$REPO_ROOT/.specify/specs/${SPECIFY_FEATURE}"
        return 0
    fi

    # Priority 2: Git branch name (if in git repo)
    if command -v git &>/dev/null && git rev-parse --git-dir &>/dev/null 2>&1; then
        local branch=$(git branch --show-current 2>/dev/null || echo "")
        if [[ -n "$branch" && "$branch" != "main" && "$branch" != "master" ]]; then
            local spec_dir="$REPO_ROOT/.specify/specs/${branch}"
            if [[ -d "$spec_dir" ]]; then
                echo "$spec_dir"
                return 0
            fi
        fi
    fi

    # Priority 3: Latest specs directory
    local latest=$(find "$REPO_ROOT/.specify/specs" -maxdepth 1 -type d 2>/dev/null | grep -E '/[0-9]+-' | sort -r | head -1)
    if [[ -n "$latest" ]]; then
        echo "$latest"
        return 0
    fi

    return 1
}

# =============================================================================
# Main execution
# =============================================================================
main() {
    local json_mode=false
    local feature_dir=""

    # Parse arguments
    if [[ "${1:-}" == "--json" ]]; then
        json_mode=true
        shift
    fi

    if [[ -n "${1:-}" ]]; then
        feature_dir="$1"
        # Convert to absolute path if relative
        if [[ "$feature_dir" != /* ]]; then
            feature_dir="$REPO_ROOT/$feature_dir"
        fi
    else
        if ! feature_dir=$(get_feature_dir); then
            if $json_mode; then
                cat << EOF
{
  "status": "error",
  "message": "No feature found. Run /speckit.specify first."
}
EOF
            else
                echo ""
                echo "━━━━━ ⚠️  Error ━━━━━"
                echo ""
                echo "No feature found"
                echo "Run /speckit.specify first to create a feature"
                echo ""
            fi
            exit 1
        fi
    fi

    # Validate feature directory exists
    if [[ ! -d "$feature_dir" ]]; then
        if $json_mode; then
            cat << EOF
{
  "status": "error",
  "message": "Feature directory not found: $feature_dir"
}
EOF
        else
            echo ""
            echo "━━━━━ ⚠️  Error ━━━━━"
            echo ""
            echo "Feature directory not found: $feature_dir"
            echo ""
        fi
        exit 1
    fi

    # Validate spec.md exists
    local spec_file="$feature_dir/spec.md"
    if [[ ! -f "$spec_file" ]]; then
        if $json_mode; then
            cat << EOF
{
  "status": "error",
  "message": "spec.md not found. Run /speckit.specify first."
}
EOF
        else
            echo ""
            echo "━━━━━ ⚠️  Error ━━━━━"
            echo ""
            echo "spec.md not found in $feature_dir"
            echo "Run /speckit.specify first"
            echo ""
        fi
        exit 1
    fi

    # Check if brand is configured (optional but recommended)
    local brand_exists="false"
    local brand_version="N/A"
    if [[ -f "$BRAND_FILE" ]]; then
        brand_exists="true"
        brand_version=$(grep -E "^version:" "$BRAND_FILE" 2>/dev/null | awk '{print $2}' | tr -d '"' || echo "1.0.0")
    fi

    # Create design.md from template if not exists
    local design_file="$feature_dir/design.md"
    local design_exists="true"
    if [[ ! -f "$design_file" ]]; then
        design_exists="false"
        if [[ -f "$TEMPLATE_FILE" ]]; then
            cp "$TEMPLATE_FILE" "$design_file"
        else
            # Fallback: create minimal design.md
            cat > "$design_file" << 'EOF'
# Design

Generated by /speckit.design

## Screens

### [Screen Name]

**Route**: /[path]

**Component Structure**: [To be filled by /speckit.design]

---

## Components to Install

```bash
npx shadcn@latest add [components]
```
EOF
        fi
    fi

    # Get feature name from directory
    local feature_name=$(basename "$feature_dir")

    # Output results
    if $json_mode; then
        cat << EOF
{
  "status": "ready",
  "feature_dir": "$feature_dir",
  "feature_name": "$feature_name",
  "spec_file": "$spec_file",
  "design_file": "$design_file",
  "design_exists": $design_exists,
  "brand_file": "${BRAND_FILE}",
  "brand_exists": $brand_exists,
  "brand_version": "$brand_version"
}
EOF
    else
        echo ""
        echo "━━━━━ 🎨 Design Setup ━━━━━"
        echo ""
        echo "Feature: $feature_name"
        echo "Spec: $spec_file"
        echo "Design: $design_file $(if [[ "$design_exists" == "false" ]]; then echo "(created)"; else echo "(exists)"; fi)"
        echo ""
        if [[ "$brand_exists" == "true" ]]; then
            echo "Brand: $BRAND_FILE (v$brand_version)"
        else
            echo "⚠️  Brand not configured - run /speckit.brand first (recommended)"
        fi
        echo ""
        echo "Ready for /speckit.design"
        echo ""
    fi
}

main "$@"
